#!/bin/bash
# Script generated by Gemini. To use:
# - make it executable:         chmod +x setup_fapi.sh
# - run it with sudo:           sudo ./setup_fapi.sh
# - log out, restart, or run:   newgrp tss

# TPM 2.0 FAPI Automated Setup Script for Ubuntu 22.04
# Fails the script immediately if any command encounters an error
set -e

# 1. Ensure the script is run with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script with sudo: sudo ./setup_fapi.sh"
  exit 1
fi

# Detect the actual user who invoked sudo
TARGET_USER="${SUDO_USER:-$USER}"

echo "========================================"
echo " Starting TPM 2.0 FAPI Compilation Setup"
echo "========================================"

echo "[1/7] Installing build dependencies..."
apt-get update
# Added 'jq' to robustly edit the JSON config
apt-get install -y build-essential autoconf autoconf-archive automake \
  libtool pkg-config gcc git libssl-dev libcurl4-openssl-dev \
  libjson-c-dev uuid-dev jq

echo "[2/7] Setting up 'tss' user and group..."
if ! id -u tss > /dev/null 2>&1; then
    useradd --system --user-group tss
fi

if [ -n "$TARGET_USER" ] && [ "$TARGET_USER" != "root" ]; then
    usermod -aG tss "$TARGET_USER"
    echo "-> User '$TARGET_USER' added to the 'tss' group."
fi

BUILD_DIR=$(mktemp -d)
cd "$BUILD_DIR"
echo "-> Working in temporary directory: $BUILD_DIR"

echo "[3/7] Compiling the Library (tpm2-tss v4.1.3)..."
git clone https://github.com/tpm2-software/tpm2-tss.git
cd tpm2-tss
git checkout 4.1.3
./bootstrap
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-udevrulesdir=/etc/udev/rules.d
make -j$(nproc)
make install

echo "-> Reloading hardware rules and linker cache..."
udevadm control --reload-rules && udevadm trigger
ldconfig

echo "[4/7] Compiling the Tools (tpm2-tools v5.6)..."
cd "$BUILD_DIR"
git clone https://github.com/tpm2-software/tpm2-tools.git
cd tpm2-tools
git checkout 5.6
./bootstrap
./configure --prefix=/usr --enable-fapi
make -j$(nproc)
make install

echo "[5/7] Applying hardware compatibility fixes..."
echo "-> Removing unsupported 3072-bit/384-bit cryptographic profiles..."
rm -f /etc/tpm2-tss/fapi-profiles/P_RSA3072SHA384.json
rm -f /etc/tpm2-tss/fapi-profiles/P_ECCP384SHA384.json

echo "-> Enabling 'ek_cert_less' mode for fTPM compatibility..."
# Use jq to safely add the property into the JSON object
jq '.ek_cert_less = "yes"' /etc/tpm2-tss/fapi-config.json > "$BUILD_DIR/fapi-config.tmp"
mv "$BUILD_DIR/fapi-config.tmp" /etc/tpm2-tss/fapi-config.json

echo "[6/7] Setting directory permissions and Provisioning..."
mkdir -p /var/lib/tpm2-tss/system/keystore
chown -R tss:tss /etc/tpm2-tss /var/lib/tpm2-tss
chmod -R 755 /etc/tpm2-tss
chmod 2775 /var/lib/tpm2-tss/system/keystore

echo "-> Clearing previous TPM state (if any)..."
tpm2_evictcontrol -C o -c 0x81000001 2>/dev/null || true
rm -rf /var/lib/tpm2-tss/system/keystore/*

echo "-> Provisioning FAPI..."
sudo -u tss tss2_provision

# Clean up
rm -rf "$BUILD_DIR"

echo "[7/7] Testing TPM Access..."
if [ -n "$TARGET_USER" ] && [ "$TARGET_USER" != "root" ]; then
    echo "-> Requesting 32 bytes of random data from the TPM hardware as user '$TARGET_USER':"
    RANDOM_HEX=$(sudo -u "$TARGET_USER" sg tss -c 'tpm2_getrandom --hex 32')
    echo "   Success! Hardware returned: $RANDOM_HEX"
fi

echo "========================================"
echo " Setup Complete! TPM FAPI is provisioned."
echo "========================================"